const CARDS = [
  {id:1,img:'assets/moonbyul_01.jpg',rarity:1,name:'별이 01'},
  {id:2,img:'assets/moonbyul_02.jpg',rarity:1,name:'별이 02'},
  {id:3,img:'assets/moonbyul_03.jpg',rarity:1,name:'별이 03'},
  {id:4,img:'assets/moonbyul_04.jpg',rarity:1,name:'별이 04'},
  {id:5,img:'assets/moonbyul_05.jpg',rarity:1,name:'별이 05'},
  {id:6,img:'assets/moonbyul_06.jpg',rarity:1,name:'별이 06'},
  {id:7,img:'assets/moonbyul_07.jpg',rarity:2,name:'별이 07'},
  {id:8,img:'assets/moonbyul_08.jpg',rarity:2,name:'별이 08'},
  {id:9,img:'assets/moonbyul_09.jpg',rarity:2,name:'별이 09'},
  {id:10,img:'assets/moonbyul_10.jpg',rarity:2,name:'별이 10'},
  {id:11,img:'assets/moonbyul_11.jpg',rarity:3,name:'별이 11'},
  {id:12,img:'assets/moonbyul_12.jpg',rarity:3,name:'별이 12'}
];
const RARITY = {1:'COMMON ✦',2:'RARE ✦✦',3:'STAR ✦✦✦'};
const DEFAULT = {coins:20000,packs:{small:0,big:0,surprise:0},owned:{},opened:0,favorites:[],level:1};
let state = load();
let filter = 'all';
function load(){try{return {...DEFAULT,...JSON.parse(localStorage.getItem('byulHandbook')||'{}')}}catch(e){return structuredClone(DEFAULT)}}
function save(){localStorage.setItem('byulHandbook',JSON.stringify(state));render()}
function toast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1600)}
function weighted(pool,weights){let total=weights.reduce((a,b)=>a+b,0),r=Math.random()*total;for(let i=0;i<pool.length;i++){r-=weights[i];if(r<=0)return pool[i]}return pool[0]}
function drawCard(kind){let rarity;if(kind==='surprise') rarity=weighted([1,2,3],[20,55,25]); else rarity=weighted([1,2,3],[72,23,5]);const pool=CARDS.filter(c=>c.rarity===rarity);return pool[Math.floor(Math.random()*pool.length)]}
function addCard(c){state.owned[c.id]=(state.owned[c.id]||0)+1}
function buy(type){const cfg={small:[2500,5],big:[4500,10],surprise:[4000,3]}[type];if(state.coins<cfg[0])return toast('⭐ 不夠喔');state.coins-=cfg[0];state.packs[type]++;save();toast('購入成功 ✦')}
function openPack(type){if(!state.packs[type])return toast('先去商店買卡包吧');state.packs[type]--;const n={small:5,big:10,surprise:3}[type];const got=[];for(let i=0;i<n;i++){const c=drawCard(type);addCard(c);got.push(c)}state.opened++;state.coins+=Math.min(700,state.opened*25);save();showReveal(got)}
function showReveal(cards){document.getElementById('openMessage').textContent=`翻出了 ${cards.length} 張 Moonbyul 卡 ✨`;document.getElementById('revealGrid').innerHTML=cards.map(c=>cardHTML(c,true)).join('')}
function cardHTML(c,revealed=false){const count=state.owned[c.id]||0,owned=count>0,fav=state.favorites.includes(c.id);return `<div class="card ${owned?'':'locked'} ${fav?'favorite':''}" data-card="${c.id}" ${revealed?'':'title="點擊加入／移出紀念冊"'}><img src="${c.img}" alt="${c.name}"><span class="count">×${count}</span><div class="shade"><div class="name">${owned?c.name:'???'}</div><div class="rarity">${RARITY[c.rarity]}</div></div></div>`}
function merge(rarity){if(rarity>=3)return;let duplicates=[];CARDS.filter(c=>c.rarity===rarity).forEach(c=>{for(let i=1;i<(state.owned[c.id]||0);i++)duplicates.push(c.id)});if(duplicates.length<3)return toast('重複卡還不夠 3 張');for(let i=0;i<3;i++){const idx=Math.floor(Math.random()*duplicates.length),id=duplicates.splice(idx,1)[0];state.owned[id]--}const pool=CARDS.filter(c=>c.rarity===rarity+1),gain=pool[Math.floor(Math.random()*pool.length)];addCard(gain);save();toast(`合成成功：${gain.name} ✨`)}
function autoMerge(){let did=false;for(let r=1;r<=2;r++){while(dupCount(r)>=3){mergeSilent(r);did=true}}save();toast(did?'一鍵合成完成 ✨':'目前沒有可合成的卡')}
function mergeSilent(rarity){let duplicates=[];CARDS.filter(c=>c.rarity===rarity).forEach(c=>{for(let i=1;i<(state.owned[c.id]||0);i++)duplicates.push(c.id)});for(let i=0;i<3;i++){const id=duplicates.splice(Math.floor(Math.random()*duplicates.length),1)[0];state.owned[id]--}const pool=CARDS.filter(c=>c.rarity===rarity+1);addCard(pool[Math.floor(Math.random()*pool.length)])}
function dupCount(r){return CARDS.filter(c=>c.rarity===r).reduce((s,c)=>s+Math.max(0,(state.owned[c.id]||0)-1),0)}
function render(){document.getElementById('coins').textContent=state.coins.toLocaleString();document.getElementById('openedStat').textContent=state.opened;document.getElementById('ownedStat').textContent=Object.values(state.owned).reduce((a,b)=>a+b,0);const discovered=CARDS.filter(c=>(state.owned[c.id]||0)>0).length;document.getElementById('collectionStat').textContent=`${discovered} / ${CARDS.length}`;document.getElementById('level').textContent=1+Math.floor(discovered/4);['small','big','surprise'].forEach(x=>document.getElementById(x+'Count').textContent=state.packs[x]||0);document.getElementById('cardGrid').innerHTML=CARDS.filter(c=>filter==='all'||(state.owned[c.id]||0)>0).map(c=>cardHTML(c)).join('');document.getElementById('albumGrid').innerHTML=state.favorites.length?state.favorites.map(id=>CARDS.find(c=>c.id===id)).filter(Boolean).map(c=>cardHTML(c)).join(''):'<p class="muted">還沒有收藏卡片。</p>';document.getElementById('mergeGroups').innerHTML=[1,2,3].map(r=>`<div class="merge-box"><h3>${RARITY[r]}</h3><p>${r<3?`可用重複卡：${dupCount(r)} / 3`:'最高稀有度，無法再升級'}</p><button ${r===3||dupCount(r)<3?'disabled':''} onclick="merge(${r})">${r===3?'MAX':'合成 →'}</button></div>`).join('')}
function switchView(v){document.querySelectorAll('.panel:not(.hero)').forEach(x=>x.classList.remove('active-view'));document.getElementById('view-'+v).classList.add('active-view');document.querySelectorAll('.nav[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));window.scrollTo({top:150,behavior:'smooth'})}
function exportCode(){const d=btoa(unescape(encodeURIComponent(JSON.stringify(state))));document.getElementById('codeTitle').textContent='📤 引繼碼';document.getElementById('codeArea').value=d;document.getElementById('codeAction').textContent='複製引繼碼';document.getElementById('codeAction').onclick=()=>navigator.clipboard.writeText(d).then(()=>toast('已複製'));document.getElementById('codeDialog').showModal()}
function importCode(){document.getElementById('codeTitle').textContent='📥 讀取引繼碼';const area=document.getElementById('codeArea');area.value='';document.getElementById('codeAction').textContent='匯入進度';document.getElementById('codeAction').onclick=()=>{try{state={...DEFAULT,...JSON.parse(decodeURIComponent(escape(atob(area.value.trim()))))};save();document.getElementById('codeDialog').close();toast('進度匯入成功')}catch(e){toast('引繼碼格式不正確')}};document.getElementById('codeDialog').showModal()}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));document.querySelectorAll('[data-pack]').forEach(b=>b.addEventListener('click',()=>buy(b.dataset.pack)));document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openPack(b.dataset.open)));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));document.getElementById('settingsBtn').onclick=()=>document.getElementById('settingsDialog').showModal();document.getElementById('albumBtn').onclick=()=>{render();document.getElementById('settingsDialog').close();document.getElementById('albumDialog').showModal()};document.getElementById('exportBtn').onclick=exportCode;document.getElementById('importBtn').onclick=importCode;document.getElementById('autoMergeBtn').onclick=autoMerge;document.getElementById('resetBtn').onclick=()=>{if(confirm('確定要清除這個瀏覽器的所有遊戲進度嗎？')){state=structuredClone(DEFAULT);save();toast('已重置')}};document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render()});document.addEventListener('click',e=>{const card=e.target.closest('.card[data-card]');if(!card||!(state.owned[card.dataset.card]>0)||card.closest('#revealGrid'))return;const id=+card.dataset.card,idx=state.favorites.indexOf(id);if(idx>=0)state.favorites.splice(idx,1);else state.favorites.push(id);save();});render();
