const MERGE_CARDS=Array.from({length:12},(_,i)=>({id:i+1,img:`assets/moonbyul_${String(i+1).padStart(2,'0')}.jpg`,rarity:i<6?1:i<10?2:3,name:`별이 ${String(i+1).padStart(2,'0')}`}));
const SET1=MERGE_CARDS.map(c=>({...c,key:`s1-${c.id}`,set:1,level:c.id,name:`SET 1 · ${String(c.id).padStart(2,'0')}`}));
const SET2=Array.from({length:53},(_,i)=>({id:i+1,key:`s2-${i+1}`,set:2,level:i+1,img:`assets/set2/set2_${String(i+1).padStart(2,'0')}.jpg`,name:`SET 2 · Lv.${i+1}`}));
const COLLECTION=[...SET1,...SET2], SELL_VALUE={1:80,2:220,3:600}, SUMMON_COST=200;
const DEFAULT={coins:20000,packs:{small:0,big:0,surprise:0},owned:{},collectionOwned:{},opened:0,favorites:[],summonTarget:3,inventoryOrder:[],missions:[{cardId:3,qty:1,reward:700},{cardId:5,qty:1,reward:1800},{cardId:7,qty:1,reward:4200}]};
let state=load(),filter='all',summonHoldTimer=null,summonRepeatTimer=null,summonDidRepeat=false,dragState=null,mergeRenderQueued=false;
function clone(x){return JSON.parse(JSON.stringify(x))}function load(){try{const x={...clone(DEFAULT),...JSON.parse(localStorage.getItem('byulHandbook')||'{}')};x.packs={...DEFAULT.packs,...x.packs};x.collectionOwned=x.collectionOwned||{};x.missions=x.missions?.length?x.missions:clone(DEFAULT.missions);return x}catch(e){return clone(DEFAULT)}}
function save(full=false){localStorage.setItem('byulHandbook',JSON.stringify(state));if(full)render()}function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1600)}
function weighted(items,weights){let r=Math.random()*weights.reduce((a,b)=>a+b,0);for(let i=0;i<items.length;i++){r-=weights[i];if(r<=0)return items[i]}return items[0]}
// Merge summon: every next level is rarer. Lv1 is common; Lv12 is a jackpot, but still possible.
function drawMergeCard(){return weighted(MERGE_CARDS,MERGE_CARDS.map(c=>Math.pow(.61,c.id-1)))}
// Collection packs: Set 1 + Set 2. Set 2 follows the supplied Level 1→53 order; higher level = lower probability.
function drawCollectionCard(kind){const surprise=kind==='surprise';const chooseSet=Math.random()<(surprise?.18:.25)?1:2;if(chooseSet===1)return weighted(SET1,SET1.map(c=>Math.pow(surprise?.88:.78,c.level-1)));return weighted(SET2,SET2.map(c=>Math.pow(surprise?.955:.91,c.level-1)))}
function addMerge(c,n=1){state.owned[c.id]=(state.owned[c.id]||0)+n}function addCollection(c,n=1){state.collectionOwned[c.key]=(state.collectionOwned[c.key]||0)+n}function totalMerge(){return Object.values(state.owned).reduce((a,b)=>a+(+b||0),0)}
function discovered(set){return set.filter(c=>(state.collectionOwned[c.key]||0)>0).length}
function renderTopStats(){document.getElementById('coins').textContent=state.coins.toLocaleString();document.getElementById('openedStat').textContent=state.opened;document.getElementById('ownedStat').textContent=totalMerge();document.getElementById('collectionStat').textContent=`${discovered(COLLECTION)} / 65`;document.getElementById('set1Stat')&&(document.getElementById('set1Stat').textContent=`${discovered(SET1)} / 12`);document.getElementById('set2Stat')&&(document.getElementById('set2Stat').textContent=`${discovered(SET2)} / 53`)}
function renderPackCounts(){['small','big','surprise'].forEach(x=>document.getElementById(x+'Count').textContent=state.packs[x]||0)}function renderSummonTarget(){document.getElementById('summonTarget').textContent=state.summonTarget||3}function queueGameplayRender(){if(mergeRenderQueued)return;mergeRenderQueued=true;requestAnimationFrame(()=>{mergeRenderQueued=false;renderTopStats();renderMergeInventory();renderMissions()})}
function buy(type){const price={small:3000,big:5500,surprise:4500}[type];if(state.coins<price)return toast('⭐ 不夠喔');state.coins-=price;state.packs[type]++;save();renderTopStats();renderPackCounts();toast('圖鑑卡包購入成功 ✦')}
function openPack(type){if(!state.packs[type])return toast('先去商店買卡包吧');state.packs[type]--;const n={small:5,big:10,surprise:3}[type],got=[];for(let i=0;i<n;i++){const c=drawCollectionCard(type);addCollection(c);got.push(c)}state.opened++;save();renderTopStats();renderPackCounts();showReveal(got)}
function showReveal(cards){document.getElementById('openMessage').textContent=`翻出了 ${cards.length} 張圖鑑卡 ✨`;document.getElementById('revealGrid').innerHTML=cards.map(c=>collectionCardHTML(c,true)).join('')}
function collectionCardHTML(c,revealed=false){const count=state.collectionOwned[c.key]||0,owned=count>0,fav=state.favorites.includes(c.key);return `<div class="card ${owned?'':'locked'} ${fav?'favorite':''}" data-collection="${c.key}"><img loading="lazy" src="${c.img}" alt="${c.name}"><span class="count">×${count}</span><div class="shade"><div class="name">${owned||revealed?c.name:'???'}</div><div class="rarity">${c.set===1?'ORIGINAL SET':`LEVEL ${c.level}`}</div></div></div>`}
function renderBook(){const root=document.getElementById('cardGrid');root.innerHTML=[{title:'SET 1 — ORIGINAL',cards:SET1},{title:'SET 2 — LEVEL 1–53',cards:SET2}].map(g=>{const cards=g.cards.filter(c=>filter==='all'||(state.collectionOwned[c.key]||0)>0);return `<section class="collection-set"><div class="set-heading"><b>${g.title}</b><span>${discovered(g.cards)} / ${g.cards.length}</span></div><div class="card-grid">${cards.length?cards.map(c=>collectionCardHTML(c)).join(''):'<p class="muted tiny">還沒有收集到這個 Set 的卡。</p>'}</div></section>`}).join('');renderTopStats()}
function renderAlbum(){const cards=state.favorites.map(k=>COLLECTION.find(c=>c.key===k)).filter(Boolean);document.getElementById('albumGrid').innerHTML=cards.length?cards.map(c=>collectionCardHTML(c)).join(''):'<p class="muted">還沒有收藏卡片。</p>'}
function inventoryItems(){const out=[];MERGE_CARDS.forEach(c=>{for(let i=0;i<(state.owned[c.id]||0);i++)out.push(c)});return out.sort((a,b)=>a.id-b.id)}
function mergeTileHTML(c){return `<div class="merge-card rarity-${c.rarity}" data-merge-id="${c.id}"><img src="${c.img}" alt="${c.name}"><span class="merge-rarity">${String(c.id).padStart(2,'0')}</span></div>`}
function renderMergeInventory(){const items=inventoryItems(),grid=document.getElementById('mergeInventory');grid.innerHTML=items.map(mergeTileHTML).join('');document.getElementById('mergeInventoryCount').textContent=`${items.length} 張`;document.getElementById('emptyMerge').style.display=items.length?'none':'block';bindMergeDrag()}
function organize(){renderMergeInventory();const g=document.getElementById('mergeInventory');g.classList.remove('organized-flash');void g.offsetWidth;g.classList.add('organized-flash');toast('已按卡號整理 ✦')}
function summonOnce(silent=false){const n=Math.max(1,Math.min(10,state.summonTarget||3)),cost=n*SUMMON_COST;if(state.coins<cost){if(!silent)toast('⭐ 不夠召喚');stopSummonHold();return false}state.coins-=cost;for(let i=0;i<n;i++)addMerge(drawMergeCard());save();queueGameplayRender();if(!silent)toast(`召喚 ${n} 張完成 ✦`);return true}
function setSummonTarget(n){state.summonTarget=Math.max(1,Math.min(10,n));save();renderSummonTarget()}function startSummonHold(e){e.preventDefault();summonDidRepeat=false;document.getElementById('summonBtn').classList.add('holding');clearTimeout(summonHoldTimer);summonHoldTimer=setTimeout(()=>{summonDidRepeat=true;summonOnce(true);summonRepeatTimer=setInterval(()=>summonOnce(true),620)},480)}function stopSummonHold(e){if(e)e.preventDefault();clearTimeout(summonHoldTimer);clearInterval(summonRepeatTimer);summonHoldTimer=summonRepeatTimer=null;document.getElementById('summonBtn')?.classList.remove('holding');if(e&&!summonDidRepeat)summonOnce(false);else if(summonDidRepeat){save();queueGameplayRender();toast('停止連續召喚')}}
function mergeSameCard(id){if(id>=12)return toast('별이 12 已是最高等級 ✦');if((state.owned[id]||0)<2)return toast('需要兩張相同卡片');state.owned[id]-=2;addMerge(MERGE_CARDS[id]);save();renderTopStats();renderMergeInventory();renderMissions();toast(`合成成功：${String(id).padStart(2,'0')} → ${String(id+1).padStart(2,'0')} ✨`)}function sellCard(id){const c=MERGE_CARDS[id-1];if(!c||(state.owned[id]||0)<1)return;state.owned[id]--;state.coins+=SELL_VALUE[c.rarity];save();renderTopStats();renderMergeInventory();renderMissions();toast(`出售 ${c.name} +${SELL_VALUE[c.rarity]} ⭐`)}function autoMerge(){let did=0;for(let id=1;id<12;id++)while((state.owned[id]||0)>=2){state.owned[id]-=2;addMerge(MERGE_CARDS[id]);did++}save();renderTopStats();renderMergeInventory();renderMissions();toast(did?`一鍵合成完成：${did} 次 ✨`:'目前沒有兩張相同的可合成卡')}
function bindMergeDrag(){document.querySelectorAll('.merge-card').forEach(el=>{el.addEventListener('pointerdown',beginPointerDrag);el.ondragstart=()=>false})}function beginPointerDrag(e){if(e.pointerType==='mouse'&&e.button!==0)return;const el=e.currentTarget;dragState={id:+el.dataset.mergeId,source:el,startX:e.clientX,startY:e.clientY,started:false};el.setPointerCapture?.(e.pointerId);el.addEventListener('pointermove',movePointerDrag);el.addEventListener('pointerup',endPointerDrag,{once:true});el.addEventListener('pointercancel',cleanupDrag,{once:true})}function movePointerDrag(e){if(!dragState)return;const dx=e.clientX-dragState.startX,dy=e.clientY-dragState.startY;if(!dragState.started&&Math.hypot(dx,dy)>8){dragState.started=true;createDragGhost(dragState.id);dragState.source.classList.add('drag-source');document.body.classList.add('is-dragging')}if(!dragState.started)return;e.preventDefault();moveGhost(e.clientX,e.clientY);highlightDropTarget(e.clientX,e.clientY)}function createDragGhost(id){const c=MERGE_CARDS[id-1],g=document.getElementById('dragGhost');g.innerHTML=`<img src="${c.img}" alt="">`;g.hidden=false}function moveGhost(x,y){document.getElementById('dragGhost').style.transform=`translate3d(${x-38}px,${y-48}px,0) rotate(3deg)`}function elementAt(x,y){return document.elementFromPoint(x,y)}function highlightDropTarget(x,y){document.querySelectorAll('.merge-card.drop-target').forEach(x=>x.classList.remove('drop-target'));document.getElementById('sellZone').classList.remove('drag-over');const el=elementAt(x,y),sell=el?.closest?.('#sellZone');if(sell)return sell.classList.add('drag-over');const target=el?.closest?.('.merge-card');if(target&&target!==dragState.source&&+target.dataset.mergeId===dragState.id)target.classList.add('drop-target')}function endPointerDrag(e){const d=dragState;if(!d)return cleanupDrag();d.source.removeEventListener('pointermove',movePointerDrag);if(!d.started)return cleanupDrag();e.preventDefault();const el=elementAt(e.clientX,e.clientY),sell=el?.closest?.('#sellZone'),target=el?.closest?.('.merge-card');cleanupDrag();if(sell)return sellCard(d.id);if(target&&target!==d.source&&+target.dataset.mergeId===d.id)return mergeSameCard(d.id);toast('拖到相同卡片上合成 ✦')}function cleanupDrag(){if(dragState?.source){dragState.source.classList.remove('drag-source');dragState.source.removeEventListener('pointermove',movePointerDrag)}dragState=null;document.body.classList.remove('is-dragging');document.querySelectorAll('.merge-card.drop-target').forEach(x=>x.classList.remove('drop-target'));document.getElementById('sellZone')?.classList.remove('drag-over');const g=document.getElementById('dragGhost');g.hidden=true;g.innerHTML='';g.style.transform=''}
function missionReward(id,qty){return Math.round((180*Math.pow(1.62,id-1)*qty)/50)*50}function newMission(ex=0){let id;do{id=2+Math.floor(Math.random()*9)}while(id===ex);const qty=id<=4?2:1;return{cardId:id,qty,reward:missionReward(id,qty)}}function submitMission(i){const m=state.missions[i];if((state.owned[m.cardId]||0)<m.qty)return toast('指定卡片數量不足');state.owned[m.cardId]-=m.qty;state.coins+=m.reward;state.missions[i]=newMission(m.cardId);save();renderTopStats();renderMergeInventory();renderMissions();toast(`任務提交成功 +${m.reward.toLocaleString()} ⭐`)}function renderMissions(){const box=document.getElementById('missionList');box.innerHTML=state.missions.map((m,i)=>{const c=MERGE_CARDS[m.cardId-1],have=state.owned[m.cardId]||0,ready=have>=m.qty;return `<div class="mission-card ${ready?'ready':''}"><img src="${c.img}"><div class="mission-copy"><b>${m.qty} 個 ${c.name}</b><span>持有 ${have}/${m.qty}</span><strong>獎勵：${m.reward.toLocaleString()} ⭐</strong></div><button class="mission-submit" data-mission="${i}" ${ready?'':'disabled'}>✓ 提交</button></div>`}).join('');box.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>submitMission(+b.dataset.mission))}
function render(){renderTopStats();renderPackCounts();renderSummonTarget();renderMergeInventory();renderMissions();renderBook();renderAlbum()}function switchView(v){document.querySelectorAll('.panel:not(.hero)').forEach(x=>x.classList.remove('active-view'));document.getElementById('view-'+v).classList.add('active-view');document.querySelectorAll('.nav[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));window.scrollTo({top:150,behavior:'smooth'});if(v==='book')renderBook();if(v==='merge'){renderMergeInventory();renderMissions();renderTopStats()}}
function exportCode(){const d=btoa(unescape(encodeURIComponent(JSON.stringify(state))));document.getElementById('codeTitle').textContent='📤 引繼碼';document.getElementById('codeArea').value=d;document.getElementById('codeAction').textContent='複製引繼碼';document.getElementById('codeAction').onclick=()=>navigator.clipboard.writeText(d).then(()=>toast('已複製'));document.getElementById('codeDialog').showModal()}function importCode(){document.getElementById('codeTitle').textContent='📥 讀取引繼碼';const a=document.getElementById('codeArea');a.value='';document.getElementById('codeAction').textContent='匯入進度';document.getElementById('codeAction').onclick=()=>{try{state={...clone(DEFAULT),...JSON.parse(decodeURIComponent(escape(atob(a.value.trim()))))};state.collectionOwned=state.collectionOwned||{};save();render();document.getElementById('codeDialog').close();toast('進度匯入成功')}catch(e){toast('引繼碼格式不正確')}};document.getElementById('codeDialog').showModal()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));document.querySelectorAll('[data-pack]').forEach(b=>b.onclick=()=>buy(b.dataset.pack));document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openPack(b.dataset.open));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.getElementById('settingsBtn').onclick=()=>document.getElementById('settingsDialog').showModal();document.getElementById('albumBtn').onclick=()=>{renderAlbum();document.getElementById('settingsDialog').close();document.getElementById('albumDialog').showModal()};document.getElementById('exportBtn').onclick=exportCode;document.getElementById('importBtn').onclick=importCode;document.getElementById('autoMergeBtn').onclick=autoMerge;document.getElementById('organizeBtn').onclick=organize;document.getElementById('summonMinus').onclick=()=>setSummonTarget((state.summonTarget||3)-1);document.getElementById('summonPlus').onclick=()=>setSummonTarget((state.summonTarget||3)+1);const sb=document.getElementById('summonBtn');sb.addEventListener('pointerdown',startSummonHold);sb.addEventListener('pointerup',stopSummonHold);sb.addEventListener('pointercancel',stopSummonHold);sb.addEventListener('contextmenu',e=>e.preventDefault());document.getElementById('resetBtn').onclick=()=>{if(confirm('確定要清除所有遊戲進度嗎？')){state=clone(DEFAULT);save();render();toast('已重置')}};document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderBook()});document.addEventListener('click',e=>{const card=e.target.closest('.card[data-collection]');if(!card||card.closest('#revealGrid'))return;const k=card.dataset.collection;if(!(state.collectionOwned[k]>0))return;const i=state.favorites.indexOf(k);i>=0?state.favorites.splice(i,1):state.favorites.push(k);save();renderBook();renderAlbum()});render();
